# goのpostgresql用
version: "3"
services:
  db:
    image: postgres:10
    container_name: "db"
    environment:
      POSTGRES_USER: feemanageuser
      POSTGRES_PASSWORD: feemanageuser
      POSTGRES_DB: feemanagedb
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  database:
    driver: local